// terminal_session.ts — production embed entry point. A desktop/web host
// supplies one AgentSource and one xterm-backed RenderSink. The session owns the
// renderer subscription, typed turn lifecycle, resume high-water mark, and an
// immutable snapshot suitable for a recoverable browser/Electron remount.

import { StatusRenderer } from "./status_renderer.js";
import type { RenderSink } from "./sink.js";
import {
  bindEventSource,
  DEFAULT_MEANINGFUL_PROGRESS_TIMEOUT_MS,
  type AgentEvent,
  type AgentSource,
  type AnimSink,
  type EventSourceTerminal,
} from "../core/agent_events.js";
import {
  TurnLifecycle,
  isTerminalTurnState,
  type TurnOutcome,
  type TurnSnapshot,
  type TurnState,
  type TurnTerminalState,
} from "../core/turn_lifecycle.js";
import { sanitizeTerm } from "./text.js";
import {
  VoiceSessionController,
  type VoiceSessionDependencies,
} from "../core/voice_session.js";

export const TERMINAL_SESSION_SNAPSHOT_VERSION = 1 as const;

/** Cursor/range offsets are Unicode code-point offsets, not UTF-16 units. */
export interface TerminalCompositionState {
  text: string;
  start: number;
  end: number;
}

export interface TerminalInputState {
  buffer: string;
  cursor: number;
  composition: TerminalCompositionState | null;
}

export interface TerminalSessionSnapshot {
  version: typeof TERMINAL_SESSION_SNAPSHOT_VERSION;
  turn: TurnSnapshot;
  transcript: readonly string[];
  input: TerminalInputState;
  /** Highest contiguous event sequence already applied to the transcript. */
  lastSequence: number;
}

/** Embed sources must support subscriber-local detach. This is the contract
 * that makes a refresh replace (rather than accumulate) subscriptions without
 * forcing a shared host transport to close. */
export interface DetachableAgentSource extends AgentSource {
  on(handler: (event: AgentEvent) => void): () => void;
}

/** A host source with an atomic replay/live-subscribe boundary. The method
 * must attach the handler and deliver every retained event with `seq` greater
 * than `lastSequence` as one ordered operation, so an event cannot fall into
 * the refresh gap between replay and live registration. */
export interface ReplayableAgentSource extends DetachableAgentSource {
  subscribeAfter(lastSequence: number, handler: (event: AgentEvent) => void): () => void;
}

export type TerminalResumeMode = "atomic" | "legacy-gap-detect";

export interface TerminalSessionOptions {
  source: DetachableAgentSource;
  sink: RenderSink;
  /** Exact submitted prompt. Kept only in the host-owned lifecycle snapshot. */
  prompt?: string;
  /** Stable external correlation id; generated by TurnLifecycle when absent. */
  turnId?: string;
  /** Recover an active or completed embed without replaying live events twice. */
  snapshot?: TerminalSessionSnapshot;
  /** Active snapshots require atomic buffered replay by default. The explicit
   * legacy mode is loss-detecting, not lossless: it uses on() and fails visibly
   * when the next observed sequence proves that an event was missed. */
  resumeMode?: TerminalResumeMode;
  /** Require every live event to carry a positive contiguous `seq`. Defaults
   * true. Set false only for a legacy/local source that cannot resume. */
  requireSequence?: boolean;
  /** Exactly-once callback for a terminal outcome produced by this mount. */
  onOutcome?: (outcome: TurnOutcome) => void;
  /** "api" shows UVT used/cap; "local" hides it. Embeds are cloud-metered → "api". */
  mode?: "local" | "api";
  /** Injected clock (ms) — overridden in tests. */
  now?: () => number;
  /** Soft stall indicator and hard meaningful-progress bound for an embed. */
  heartbeatTimeoutMs?: number;
  meaningfulProgressTimeoutMs?: number;
  /** Close the underlying source when the turn ends. False keeps a host-owned,
   * shared transport alive and detaches only this session's subscriber. */
  ownsSource?: boolean;
  /** Optional host-owned audio ports plus the host's existing conversation
   * send bridge. Construction never requests microphone permission. */
  voice?: VoiceSessionDependencies;
}

export interface TerminalSession {
  /** Null unless the embed supplied a complete Voice port bundle. */
  readonly voice: VoiceSessionController | null;
  /** Stable aliases for support/log correlation across remounts. */
  readonly turnId: string;
  readonly correlationId: string;
  readonly state: TurnState;
  readonly outcome: TurnOutcome | null;
  /** Replace host-owned editor state so it survives the next remount. */
  setInputState(input: TerminalInputState): void;
  /** A defensive clone; mutating it cannot change the live session. */
  snapshot(): TerminalSessionSnapshot;
  /** Explicit semantic cancellation. dispose() is only a UI unmount. */
  cancel(message?: string): TurnOutcome;
  dispose(): void;
}

const EMPTY_INPUT: TerminalInputState = Object.freeze({
  buffer: "",
  cursor: 0,
  composition: null,
});

export function createTerminalSession(opts: TerminalSessionOptions): TerminalSession {
  const restored = opts.snapshot ? normalizeSessionSnapshot(opts.snapshot) : null;
  const resumeMode = opts.resumeMode ?? "atomic";
  if (resumeMode !== "atomic" && resumeMode !== "legacy-gap-detect") {
    throw new TypeError("unsupported terminal resume mode");
  }
  if (restored && opts.prompt != null && opts.prompt !== restored.turn.prompt) {
    throw new TypeError("terminal session snapshot does not match the submitted prompt");
  }
  const prompt = restored?.turn.prompt ?? opts.prompt ?? "";
  const lifecycle = new TurnLifecycle(prompt, {
    id: opts.turnId,
    now: opts.now,
    ...(restored ? { resume: restored.turn } : {}),
  });
  if (lifecycle.state === "idle") lifecycle.transition("submitted");
  if (lifecycle.state === "submitted") lifecycle.transition("connecting");
  const replaySource = isReplayableAgentSource(opts.source) ? opts.source : null;
  if (restored && !isTerminalTurnState(lifecycle.state) && resumeMode === "atomic" && !replaySource) {
    throw new TypeError(
      "active terminal remount requires source.subscribeAfter(lastSequence, handler); " +
      'use resumeMode: "legacy-gap-detect" only when lossless buffered replay is unavailable',
    );
  }
  const now = opts.now ?? Date.now;
  const meaningfulProgressTimeoutMs = opts.meaningfulProgressTimeoutMs ??
    DEFAULT_MEANINGFUL_PROGRESS_TIMEOUT_MS;
  const initialMeaningfulProgressRemainingMs = restored && meaningfulProgressTimeoutMs > 0
    ? Math.max(0, meaningfulProgressTimeoutMs - Math.max(0, now() - lifecycle.lastMeaningfulActivityAt))
    : undefined;

  let disposed = false;
  let renderingEnded = false;
  let outcomeNotified = lifecycle.outcome != null;
  const transcript = restored ? [...restored.transcript] : [];
  let input = restored ? cloneInput(restored.input) : cloneInput(EMPTY_INPUT);
  let lastSequence = restored?.lastSequence ?? 0;
  // A restored high-water mark can never safely fall back to an unsequenced
  // source. Fresh legacy/local embeds may opt out explicitly.
  const enforceSequence = restored != null || (opts.requireSequence ?? true);
  const useAtomicSubscription = enforceSequence && replaySource != null &&
    (restored == null || resumeMode === "atomic");
  let sequenceFailed = false;
  const voice = opts.voice ? new VoiceSessionController(opts.voice) : null;

  const renderer = new StatusRenderer({
    sink: opts.sink,
    mode: opts.mode ?? "api",
    now: opts.now,
    ownsProcess: false, // embeds never install global process handlers
  });
  renderer.start();

  // Rehydration happens once, before the sole source subscription is created.
  // These writes deliberately bypass transcript capture: the entries already
  // exist in the restored model and must not be appended again.
  for (const line of transcript) renderer.log(line);

  const canWrite = (): boolean => !disposed && !renderingEnded;
  const appendLine = (line: string): void => {
    if (!canWrite()) return;
    const safe = safeTranscriptLine(line);
    transcript.push(safe);
    renderer.log(safe);
  };
  const endRenderer = (): void => {
    if (disposed || renderingEnded) return;
    renderingEnded = true;
    renderer.end();
  };

  const anim: AnimSink = {
    setStage: (stage: string): void => { if (canWrite()) renderer.setVerb(stage, ""); },
    setProgress: (used: number, cap: number): void => { if (canWrite()) renderer.setProgress(used, cap); },
    markStalled: (): void => { if (canWrite()) renderer.setHeartbeat("○"); },
    resume: (): void => { if (canWrite()) renderer.setHeartbeat("◉"); },
    stop: (): void => {},
  };

  const advanceForEvent = (event: AgentEvent): void => {
    if (
      lifecycle.outcome ||
      event.type === "heartbeat" ||
      event.type === "done" ||
      event.type === "error" ||
      event.type === "closed"
    ) return;
    if (event.type === "tool") {
      if (lifecycle.state === "connecting" || lifecycle.state === "streaming") {
        lifecycle.transition("waiting_for_tool");
      } else {
        lifecycle.meaningfulActivity();
      }
      return;
    }
    if (lifecycle.state === "connecting" || lifecycle.state === "waiting_for_tool") {
      lifecycle.transition("streaming");
    } else {
      lifecycle.meaningfulActivity();
    }
  };

  const notifyOutcome = (outcome: TurnOutcome): void => {
    if (outcomeNotified) return;
    outcomeNotified = true;
    try {
      opts.onOutcome?.({ ...outcome });
    } catch {
      // A host callback cannot prevent renderer/source cleanup or cause a
      // second finalization. The immutable outcome remains queryable.
    }
  };

  const finish = (
    state: TurnTerminalState,
    message: string,
    details: { hint?: string | null; retryable?: boolean } = {},
  ): TurnOutcome => {
    const existing = lifecycle.outcome;
    if (existing) return existing;
    if (state === "succeeded" && lifecycle.state !== "completing") {
      lifecycle.transition("completing");
    }
    const outcome = lifecycle.finalize(state, { message, ...details });
    appendLine(outcomeLine(outcome));
    notifyOutcome(outcome);
    return outcome;
  };

  const onTerminal = (terminal: EventSourceTerminal): void => {
    if (terminal.state === "succeeded") {
      finish("succeeded", terminal.message);
    } else if (terminal.state === "timed_out") {
      finish("timed_out", terminal.message, { retryable: true });
    } else if (terminal.state === "incomplete") {
      finish("incomplete", terminal.message, { retryable: true });
    } else {
      finish("failed", terminal.message);
    }
  };

  const sequencedSource: AgentSource = {
    on(handler): () => void {
      const subscribeAfter = lastSequence;
      const accept = (event: AgentEvent): void => {
        if (disposed || renderingEnded || sequenceFailed) return;
        // EOF is an out-of-band transport fact rather than a server frame; it
        // remains terminal-incomplete even when no next sequence exists.
        if (event.type === "closed") {
          handler(event);
          return;
        }
        if (!enforceSequence) {
          handler(event);
          return;
        }
        const seq = event.seq;
        if (seq == null) {
          sequenceFailed = true;
          handler({ type: "error", message: `terminal event sequence missing after ${lastSequence}` });
          return;
        }
        if (!Number.isSafeInteger(seq) || seq <= 0) {
          sequenceFailed = true;
          handler({ type: "error", message: "terminal event carried an invalid sequence id" });
          return;
        }
        if (seq <= lastSequence) return; // replay from a resumed transport
        if (seq !== lastSequence + 1) {
          sequenceFailed = true;
          handler({
            type: "error",
            message: `terminal event sequence gap: expected ${lastSequence + 1}, received ${seq}`,
          });
          return;
        }
        lastSequence = seq;
        handler(event);
      };
      return useAtomicSubscription
        ? replaySource.subscribeAfter(subscribeAfter, accept)
        : opts.source.on(accept);
    },
    close(): void {
      opts.source.close();
    },
  };

  let unbind = (): void => {};
  if (!isTerminalTurnState(lifecycle.state)) {
    unbind = bindEventSource(
      sequencedSource,
      { log: appendLine, end: endRenderer },
      anim,
      {
        heartbeatTimeoutMs: opts.heartbeatTimeoutMs,
        meaningfulProgressTimeoutMs,
        initialMeaningfulProgressRemainingMs,
        ownsSource: opts.ownsSource,
        onMeaningfulEvent: advanceForEvent,
        onTerminal,
        renderTerminalOutput: false,
      },
    );
  } else {
    endRenderer();
  }

  return {
    voice,
    get turnId(): string { return lifecycle.id; },
    get correlationId(): string { return lifecycle.id; },
    get state(): TurnState { return lifecycle.state; },
    get outcome(): TurnOutcome | null { return lifecycle.outcome; },
    setInputState(next: TerminalInputState): void {
      input = normalizeInput(next);
    },
    snapshot(): TerminalSessionSnapshot {
      return {
        version: TERMINAL_SESSION_SNAPSHOT_VERSION,
        turn: lifecycle.snapshot(),
        transcript: [...transcript],
        input: cloneInput(input),
        lastSequence,
      };
    },
    cancel(message = "turn cancelled by host"): TurnOutcome {
      const outcome = finish("cancelled", safeTranscriptLine(message), { retryable: true });
      voice?.cancel();
      unbind();
      endRenderer();
      return outcome;
    },
    dispose(): void {
      if (disposed) return;
      disposed = true;
      voice?.dispose();
      unbind();
      if (!renderingEnded) {
        renderingEnded = true;
        renderer.end();
      }
    },
  };
}

function normalizeSessionSnapshot(value: TerminalSessionSnapshot): TerminalSessionSnapshot {
  if (!value || typeof value !== "object" || value.version !== TERMINAL_SESSION_SNAPSHOT_VERSION) {
    throw new TypeError("unsupported terminal session snapshot version");
  }
  if (!Array.isArray(value.transcript) || value.transcript.some((line) => typeof line !== "string")) {
    throw new TypeError("terminal session snapshot transcript is malformed");
  }
  if (!value.turn || typeof value.turn !== "object") {
    throw new TypeError("terminal session snapshot turn is malformed");
  }
  if (!Number.isSafeInteger(value.lastSequence) || value.lastSequence < 0) {
    throw new TypeError("terminal session snapshot lastSequence is invalid");
  }
  return {
    version: TERMINAL_SESSION_SNAPSHOT_VERSION,
    turn: {
      ...value.turn,
      outcome: value.turn.outcome ? { ...value.turn.outcome } : null,
    },
    transcript: value.transcript.map(safeTranscriptLine),
    input: normalizeInput(value.input),
    lastSequence: value.lastSequence,
  };
}

function normalizeInput(value: TerminalInputState): TerminalInputState {
  if (!value || typeof value !== "object" || typeof value.buffer !== "string") {
    throw new TypeError("terminal input snapshot is malformed");
  }
  const width = [...value.buffer].length;
  if (!Number.isSafeInteger(value.cursor) || value.cursor < 0 || value.cursor > width) {
    throw new TypeError("terminal input cursor is outside the buffer");
  }
  const composition = value.composition;
  if (composition == null) return { buffer: value.buffer, cursor: value.cursor, composition: null };
  if (
    typeof composition !== "object" ||
    typeof composition.text !== "string" ||
    !Number.isSafeInteger(composition.start) ||
    !Number.isSafeInteger(composition.end) ||
    composition.start < 0 ||
    composition.end < composition.start ||
    composition.end > width
  ) {
    throw new TypeError("terminal input composition range is invalid");
  }
  return {
    buffer: value.buffer,
    cursor: value.cursor,
    composition: { ...composition },
  };
}

function cloneInput(value: TerminalInputState): TerminalInputState {
  return {
    buffer: value.buffer,
    cursor: value.cursor,
    composition: value.composition ? { ...value.composition } : null,
  };
}

function safeTranscriptLine(value: string): string {
  return sanitizeTerm(String(value)).replace(/[\r\n\t]+/g, " ");
}

function outcomeLine(outcome: TurnOutcome): string {
  const mark = outcome.state === "succeeded" ? "✓" : "!";
  return `${mark} ${outcome.message} · ${outcome.turnId}`;
}

function isReplayableAgentSource(source: DetachableAgentSource): source is ReplayableAgentSource {
  return typeof (source as Partial<ReplayableAgentSource>).subscribeAfter === "function";
}
